import Ember from 'ember';

export default Ember.Service.extend({
  PLANS: {
    free: {
      id: 'free',
      name: 'Free',
      price: 0,
      numDiffs: 500,
      numWorkersTitle: '2 parallel workers',
      numProjectsTitle: '1 private repository',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '7 day history',
    },
    small: {
      id: 'v1-small',
      name: 'Small',
      price: 49,
      numDiffs: 5000,
      numWorkersTitle: '5 parallel workers',
      numProjectsTitle: '5 private repositories',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '14 day history',
    },
    medium: {
      id: 'v1-medium',
      name: 'Medium',
      price: 149,
      numDiffs: 25000,
      numWorkersTitle: '10 parallel workers',
      numProjectsTitle: '20 private repositories',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '30 day history',
    },
    large: {
      id: 'v1-large',
      name: 'Large',
      price: 299,
      numDiffs: 50000,
      numWorkersTitle: '15 parallel workers',
      numProjectsTitle: '50 private repositories',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '60 day history',
    },
    pro: {
      id: 'v1-pro',
      name: 'Pro',
      price: 499,
      numDiffs: 100000,
      numWorkersTitle: '20 parallel workers',
      numProjectsTitle: 'Unlimited repositories',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '90 day history',
    },
    premium: {
      id: 'v1-premium',
      name: 'Premium',
      price: 749,
      numDiffs: 150000,
      numWorkersTitle: '25 parallel workers',
      numProjectsTitle: 'Unlimited repositories',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '90 day history',
    },
    premiumXl: {
      id: 'v1-premium-xl',
      name: 'Premium XL',
      price: 990,
      numDiffs: 200000,
      numWorkersTitle: '30 parallel workers',
      numProjectsTitle: 'Unlimited repositories',
      numUsersTitle: 'Unlimited users',
      historyLimitTitle: '90 day history',
    },
  },
});
